SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Reply';

SELECT	COLUMN_NAME + ' ' + 
		case when DATA_TYPE = 'int' then DATA_TYPE
		      when DATA_TYPE = 'varchar' then DATA_TYPE + '(' + cast(CHARACTER_MAXIMUM_LENGTH as varchar(10)) + ')'
			  else DATA_TYPE end
		+ ',' as TYPE

FROM	INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Reply' and COLUMN_NAME <> 'id';

SELECT	 COLUMN_NAME
		,case when DATA_TYPE = 'int' then DATA_TYPE
		      when DATA_TYPE = 'varchar' then DATA_TYPE + '(' + cast(CHARACTER_MAXIMUM_LENGTH as varchar(10)) + ')'
			  else DATA_TYPE end TYPE

		,CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Reply' and COLUMN_NAME <> 'id';

SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Reply' and COLUMN_NAME <> 'id';
